# Generated by Django 2.1.5 on 2019-02-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190211_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='actId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='upvote',
            field=models.IntegerField(default=0),
        ),
    ]
