# Generated by Django 2.1.5 on 2019-02-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190211_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='image',
            field=models.TextField(blank=True, default=None),
        ),
    ]
