# Generated by Django 2.1.7 on 2019-03-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190318_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='actId',
            field=models.IntegerField(blank=True, default=0, unique=True),
        ),
    ]
