version: '3'

services:
  acts:
    image: acts
    build: .
    command: >
      sh -c "sudo apt-get install gunicorn3 &&
             python manage.py collectstatic --noinput &&
             sleep 2 &&
             python manage.py makemigrations --noinput &&
             python manage.py migrate --noinput &&
             gunicorn3 --reload cloud_project.wsgi:application -b 0.0.0.0:8000 --error-logfile gunicorn.error"
    volumes:
      - .:/acts
    ports:
      - "8000:8000"
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static/:/acts/static/
      - ./static/:/users/static/
    depends_on:
      - acts
volumes:
  acts:
  nginx_conf:
  static: