# Generated by Django 2.1.5 on 2019-02-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190211_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='actId',
            field=models.IntegerField(null=True),
        ),
    ]
