# Generated by Django 2.1.5 on 2019-02-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_act_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='act',
            name='upvote',
            field=models.IntegerField(default=0),
        ),
    ]
