# Generated by Django 2.1.5 on 2019-02-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190211_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='actId',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='act',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
    ]
